<?php

// /**
//  * Returns nid(s) based on a supplied pgh item key id.
//  *
//  * @param string $key
//  *   A category key.
//  *
//  * @param string $type
//  *   Type of the item
//  *
//  * @param bool $all
//  *   If all matching nid are returned, or just the first one, default FALSE
//  *
//  * @return int
//  *   The nid for the supplied id or 0 if not found.
//  *   Or array of nids if $all = TRUE
//  *
//  * @author Fang Jin <fang@designhammer.com>
//  */
// function pgh_api_find_nid($key, $type, $all = FALSE) {
//   $query = new EntityFieldQuery();
//   $result = $query->entityCondition('entity_type', 'node')
//                   ->propertyCondition('type', $type)
//                   ->propertyCondition('title', $key)
//                   ->execute();
//   if (!empty($result['node'])) {
//     $keys = array_keys($result['node']);
//     if ($all) {
//       return $keys;
//     }
//     else {
//       return $keys[0];
//     }
//   }
//   else {
//     return 0;
//   }
// }

/**
 * Returns node nid(s) based on a supplied entity and property conditions.
 *
 * @param array $property_conds
 *   Type of the item
 *
 * @param array $field_conds
 *   Type of the item
 *   By default, if item is a single value, it'll use key.`value` = value rule,
 *   Or if it's an array, it'll use full key.value[0] value[2] value[1] where
 *   value[2] is the operator if set, ex. '!='
 *
 * @param bool $all
 *   If all matching nid are returned, or just the first one, default FALSE
 *
 * @param array $entity_conds
 *   A category key.
 *
 * @return int
 *   The nid for the supplied id or 0 if not found.
 *   Or array of nids if $all = TRUE
 *
 * @author Fang Jin <fjin@qplot.com>
 */
function qplot_api_find_nodes($property_conds = NULL, $field_conds = NULL, $all = FALSE, $entity_conds = NULL, $orders = NULL) {
  $query = new EntityFieldQuery();
  $entity_default = array(
    'entity_type' => 'node'
  );
  if (!empty($entity_conds)) {
    $entity_conds = array_merge($entity_default, $entity_conds);
  } else {
    $entity_conds = $entity_default;
  }
  foreach ($entity_conds as $key => $value) {
    $query->entityCondition($key, $value);
  }
  if (!empty($property_conds)) {
    foreach ($property_conds as $key => $value) {
      $query->propertyCondition($key, $value);
    }
  }
  if (!empty($field_conds)) {
    foreach ($field_conds as $key => $value) {
      if (is_array($value)) {
        $property = isset($value[1]) ? $value[0] : 'value'; 
        $assigned = isset($value[1]) ? $value[1] : $value[0];
        $operator = isset($value[2]) ? $value[2] : '=';
        $query->fieldCondition($key, $property, $assigned, $operator);
      } else {
        $query->fieldCondition($key, 'value', $value);
      }
    }
  }
  if (!empty($orders)) {
    if (!empty($orders['field'])) {
      foreach ($orders['field'] as $key => $value) {
        $query->fieldOrderBy($key, $value[0], $value[1]);
      }
    }
    if (!empty($orders['property'])) {
      foreach ($orders['property'] as $key => $value) {
        $query->propertyOrderBy($key, $value);
      }
    }
  }

  $result = $query->execute();
  $ctype = $entity_default['entity_type'];
  if (!empty($result[$ctype])) {
    $keys = array_keys($result[$ctype]);
    if ($all) {
      return $keys;
    }
    else {
      return $keys[0];
    }
  } else {
    if ($all) {
      return array();
    } else {
      return 0;
    }
  }
}

/**
 * Candidates for new find node function
 */
function qplot_api_find_nodes2($commands) {
  $commands = array(
    array('property', 'condition', 'type', 'phase'),
    array('field', 'condition', 'field_phase_project', 'target_id', 3, '='),
    array('property', 'order', 'created', 'ASC'),
    array('array', TRUE)
  );
}