<?php



/**
 * Implements hook_menu().
 */
// function qplot_progress_menu() {
 
//   // $items['devel/cache/clear'] = array(
//   //   'title' => 'Empty cache',
//   //   'page callback' => 'devel_cache_clear',
//   //   'description' => 'Clear the CSS cache and all database cache tables which store page, node, theme and variable caches.',
//   //   'access arguments' => array('access devel information'),
//   //   'file' => 'devel.pages.inc',
//   //   'menu_name' => 'devel',
//   // );

  
//   return $items;
// }

/**
 * Implementation of hook_theme()
 */
function qplot_progress_theme() {
  return array(
    'qplot_progress_logo_area' => array(
      'variables' => array(),
      'template' => 'logo_area'
    ),
    'qplot_progress_company_teaser' => array(
      'variables' => array('company' => NULL),
      'template' => 'company_teaser'
    ),
    'qplot_progress_projects_teaser' => array(
      'variables' => array('items' => NULL),
      'template' => 'projects_teaser'
    ),
    'qplot_progress_project_overview' => array(
      'variables' => array('project' => NULL, 'items' => NULL),
      'template' => 'project_overview'
    ),
    'qplot_progress_company_overview' => array(
      'variables' => array('company' => NULL, 'contacts' => NULL),
      'template' => 'company_overview'
    ),
  );
}

/**
 * Implementation of hook_block_info()
 */
function qplot_progress_block_info() {
  $blocks = array(
    // QPlot Company logo area
    'logo_area' => array(
      'info' => ('Logo Area')
    ),
    // Company mini teaser in sidebar menu area
    'company_teaser' => array(
      'info' => ('Company Teaser')
    ),
    // Projects mini teasers in sidebar menu area
    'projects_teaser' => array(
      'info' => ('Projects Teaser')
    ),
    // Project overview teaser in main content area
    'project_overview' => array(
      'info' => ('Project Overview')
    ),
    // Company overview teaser in main content area
    'company_overview' => array(
      'info' => ('Company Overview')
    ),
  );

  return $blocks;
}

/**
 * Implementation of hook_block_view()
 */
function qplot_progress_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'logo_area':
      $block['content'] = theme('qplot_progress_logo_area');
      break;
    case 'company_teaser':
      // find company info and asoociated properties
      $node = node_load(4);
      $wrapper = entity_metadata_wrapper('node', $node);
      $variables['company'] = array(
        'title' => $wrapper->title->value(),
        'logo' => $wrapper->field_company_logo->file->url->value(),
        'description' => $wrapper->body->summary->value(),
        'status' => 'Active',
        'edit' => url('node/' . $wrapper->getIdentifier() . '/edit', array(
          'query' => drupal_get_destination()
        )),
      );

      $block['content'] = theme('qplot_progress_company_teaser', $variables);
      break;
    case 'projects_teaser':
      // find out all projects and associated properties
      $variables['items'] = array();
      $nids = qplot_api_find_nodes(
        array('type' => 'project'),
        array('field_project_company' => array(
          'target_id', 4, '='
        )),
        TRUE
      );
      foreach ($nids as $id) {
        $node = node_load($id);
        $wrapper = entity_metadata_wrapper('node', $node);
        $variables['items'][] = array(
          'title' => $wrapper->title->value(),
          'icon' => $wrapper->field_project_icon->name->value(),
          'description' => $wrapper->body->summary->value(),
          'progress' => $wrapper->field_project_progress->value(),
          'status' => $wrapper->field_project_status->name->value(),
        );
      }
      $block['content'] = theme('qplot_progress_projects_teaser', $variables);
      break;
    case 'project_overview':
      // find project info
      $node = node_load(10);
      $wrapper = entity_metadata_wrapper('node', $node);
      $variables['project'] = array(
        'title' => $wrapper->title->value(),
        'photo' => $wrapper->field_project_photo->file->url->value(),
        'icon' => $wrapper->field_project_icon->name->value(),
        'description' => $wrapper->body->summary->value(),
        'progress' => $wrapper->field_project_progress->value(),
        'status' => $wrapper->field_project_status->name->value(),
        'company' => $wrapper->field_project_company->title->value(),
        'edit' => url('node/' . $wrapper->getIdentifier() . '/edit', array(
          'query' => drupal_get_destination()
        )),
      );
      // find phases info and associate properties
      $variables['items'] = array();
      $nids = qplot_api_find_nodes(
        array('type' => 'phase'),
        array('field_phase_project' => array(
          'target_id', 10, '='
        )),
        TRUE
      );
      foreach ($nids as $id) {
        $node = node_load($id);
        $wrapper = entity_metadata_wrapper('node', $node);
        $variables['items'][] = array(
          'title' => $wrapper->title->value(),
          'description' => ($wrapper->body->raw()) ? $wrapper->body->summary->value() : '',
          'progress' => $wrapper->field_phase_progress->value(),
        );
      }

      $block['content'] = theme('qplot_progress_project_overview', $variables);
      break;
    case 'company_overview':
      // find company info
      $node = node_load(4);
      $wrapper = entity_metadata_wrapper('node', $node);
      $variables['company'] = array(
        'title' => $wrapper->title->value(),
        'logo' => $wrapper->field_company_logo->file->url->value(),
        'description' => $wrapper->body->summary->value(),
        'edit' => url('node/' . $wrapper->getIdentifier() . '/edit', array(
          'query' => drupal_get_destination()
        )),
      );

      // find company contacts 
      $variables['contacts'] = array();
      foreach ($wrapper->field_company_contacts->getIterator() as $cwrapper) {
        $variables['contacts'][] = array(
          'name' => $cwrapper->title->value(),
          'title' => $cwrapper->field_contact_title->value(),
          'photo' => $cwrapper->field_contact_photo->file->url->value(),
          'email' => $cwrapper->field_contact_email->value(),
          'phone' => $cwrapper->field_contact_phone->value()
        );
      }

      $block['content'] = theme('qplot_progress_company_overview', $variables);
      break;
    
    default:
      # code...
      break;
  }

  return $block;
}

// function theme_devel_querylog_row($variables) {
//   $row = $variables['row'];
//   $i = 0;
//   $output = '';
//   foreach ($row as $cell) {
//     $i++;

//     if (is_array($cell)) {
//       $data = !empty($cell['data']) ? $cell['data'] : '';
//       unset($cell['data']);
//       $attr = $cell;
//     }
//     else {
//       $data = $cell;
//       $attr = array();
//     }

//     if (!empty($attr['class'])) {
//       $attr['class'] .= " cell cell-$i";
//     }
//     else {
//       $attr['class'] = "cell cell-$i";
//     }
//     $attr = drupal_attributes($attr);

//     $output .= "<div $attr>$data</div>";
//   }
//   return $output;
// }
